language: node_js
node_js:
  - 0.10

branches:
  except:
    - /^g3_.*$/

env:
  matrix:
    - JOB=unit BROWSER_PROVIDER=sl
    - JOB=e2e TEST_TARGET=jqlite BROWSER_PROVIDER=sl
    - JOB=e2e TEST_TARGET=jquery BROWSER_PROVIDER=sl
    - JOB=e2e TEST_TARGET=doce2e BROWSER_PROVIDER=sl
  global:
    - SAUCE_USERNAME=angular-ci
    - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987
    - LOGS_DIR=/tmp/angular-build/logs
    - BROWSER_PROVIDER_READY_FILE=/tmp/tunnel-ready

install:
  - npm config set registry http://23.251.144.68
  # Run npm install twice, because it is flaky.
  - npm install || npm install

before_script:
  - mkdir -p $LOGS_DIR
  - ./scripts/travis/start_browser_provider.sh
  - npm install -g grunt-cli
  - grunt package
  - ./scripts/travis/wait_for_browser_provider.sh

script:
  - ./scripts/travis/build.sh

after_script:
  - ./scripts/travis/print_logs.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2120f3f2bb39a4531b2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
